; a. How many times is the procedure p applied when (sine 12.15) is evaluated?
; b. What is the order of growth in space and number of steps (as a function of a) 
; used by the process generated by the sine procedure when (sine a) is evaluated?
 
 "a. the procedure p is applied 6 times"
 "b. the order of growth in space and the growth in steps is O(log(a))"